# Homework 1
**Sakina Lord**

*STA 556 | Fall 2026*

In [58]:
import pandas as pd
import numpy as np

In [59]:
courses = pd.read_csv("data/raw/courses.csv")

enrollments = pd.read_csv("data/raw/enrollments.csv")

students = pd.read_csv("data/raw/students.csv")

# Part 1: Inspect the data
For each table:
1. load it with pandas;
2. report its shape;
3. identify its columns and dtypes;
4. count missing values;
5. identify the likely key column(s).

Write 3–5 sentences describing any immediate data-quality concerns.

In [60]:
print(f"{courses.shape = }\n")
print(f"{courses.columns = }\n")
print(f"{courses.dtypes = }\n")
print(f"{courses.isna().sum() = }\n")

courses.shape = (8, 7)

courses.columns = Index(['course_id', 'department', 'course_number', 'course_title', 'credits',
       'level', 'delivery'],
      dtype='str')

courses.dtypes = course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object

courses.isna().sum() = course_id        0
department       0
course_number    0
course_title     0
credits          0
level            0
delivery         0
dtype: int64

In [61]:
print(f"{enrollments.shape = }\n")
print(f"{enrollments.columns = }\n")
print(f"{enrollments.dtypes = }\n")
print(f"{enrollments.isna().sum() = }\n")

enrollments.shape = (59, 9)

enrollments.columns = Index(['enrollment_id', 'student_id', 'course_id', 'term', 'status',
       'midterm_score', 'final_score', 'project_score', 'attendance_pct'],
      dtype='str')

enrollments.dtypes = enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object

enrollments.isna().sum() = enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64

In [62]:
print(f"{students.shape = }\n")
print(f"{students.columns = }\n")
print(f"{students.dtypes = }\n")
print(f"{students.isna().sum() = }\n")

students.head()

students.shape = (30, 11)

students.columns = Index(['student_id', 'first_name', 'last_name', 'program', 'year', 'age',
       'active', 'entry_term', 'gpa', 'credits_completed', 'advisor'],
      dtype='str')

students.dtypes = student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object

students.isna().sum() = student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim
4,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18,Dr. Kim

**Key Columns:**

Courses: course_id

Enrollments: enrollment_id (primary), course_id, student_id

Students: student_id

**Data Quality Concerns**

5 of the 59 enrollments entries have no final score. There is also missingness for project_score and attendance_pct. The Students table has missing ages, gpas, and advisor. 3 of the 30 students (10%) have a missing gpa. Another issue we might run into when completing joins is the overlap between IDs. There are 59 enrollment entries linking a student to a course and 30 students. Not all students might be equally represented after the joins.

# Part 2: Filtering and derived variables

Using the student-level table:
1. select a meaningful subset using at least two conditions;
2. create one derived variable;
3. use .loc[] correctly;
4. demonstrate one list or dictionary comprehension related to the data.

Briefly explain your choices

In [63]:
non_trad_students = students.loc[
    (students["age"] >= 21.0) & (students["year"] != "4th")
]

non_trad_students

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno
6,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36,Dr. Kim
8,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45,Dr. Moreno
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
20,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30,Dr. Shah
23,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45,Dr. Kim
26,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36,Dr. Kim

In [64]:
non_trad_students["above_avg_gpa"] = "No"
non_trad_students.loc[
    non_trad_students["gpa"] > students["gpa"].mean(),
    "above_avg_gpa"] = "Yes"

non_trad_students

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,above_avg_gpa
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,Yes
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,No
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno,Yes
6,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36,Dr. Kim,Yes
8,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45,Dr. Moreno,No
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah,Yes
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno,Yes
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah,Yes
20,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30,Dr. Shah,Yes
23,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45,Dr. Kim,Yes
26,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36,Dr. Kim,Yes

I chose to select the subset of students who were potentially on a non-traditional college path, which are often older students returning to college or those who did not immediately enter college upon completing highschool. 21 is a common age for 4th year students, so I chose to select only students older than 21 who were not yet in their fourth year.

I used list comprehension to create the derived variable `above_avg_gpa`, which indicates whether or not the student's GPA is above or below the average of all the students in the dataset. This could be modified to reflect only the students in the subset as well.

# Part 3: Joining Tables

Combine the three tables into one analysis dataset.

Before each merge:
1. state the expected relationship;
2. use an appropriate how=;
3. use validate=;
4. inspect unmatched rows with indicator=True at least once.

Explain any duplicated rows created by a one-to-many relationship.

In [65]:
# Merge Enrollments and Students using a Left Join (we only want courses students are enrolled in)
enrolled_students = enrollments.merge(
    students,
    how = "left",
    left_on = "student_id",
    right_on = "student_id",
    validate = "m:1", # Many enrollments to one student
)

enrolled_students.isna().sum()

enrollment_id        0
student_id           0
course_id            0
term                 0
status               0
midterm_score        0
final_score          5
project_score        3
attendance_pct       2
first_name           1
last_name            1
program              1
year                 1
age                  5
active               1
entry_term           1
gpa                  5
credits_completed    1
advisor              2
dtype: int64

In [66]:
print(f"Number of Duplicates: {enrolled_students.duplicated().sum()}")
enrolled_students.head()

Number of Duplicates: 0

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,E5001,S1001,C102,Spring 2026,Completed,96,65.0,65.0,94.7,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno
1,E5002,S1001,C106,Spring 2026,Completed,81,80.0,63.0,96.6,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno
2,E5003,S1001,C103,Spring 2026,Completed,77,67.0,72.0,88.6,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno
3,E5004,S1002,C106,Fall 2025,Completed,86,NaN,85.0,77.3,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah
4,E5005,S1002,C101,Fall 2025,Completed,90,55.0,79.0,85.8,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah

In [67]:
# Merge the enrolled_students with courses, again with a Left join, students may attend multiple courses
final_df = enrolled_students.merge(
    courses,
    how = "left",
    left_on = "course_id",
    right_on = "course_id",
    validate = "m:1", # Many enrollments to one course
    indicator=True
)

print(f"NAs: \n{final_df.isna().sum()}")
print(f"Number of Duplicates: {final_df.duplicated().sum()}")
final_df.head()

NAs:
enrollment_id        0
student_id           0
course_id            0
term                 0
status               0
midterm_score        0
final_score          5
project_score        3
attendance_pct       2
first_name           1
last_name            1
program              1
year                 1
age                  5
active               1
entry_term           1
gpa                  5
credits_completed    1
advisor              2
department           1
course_number        1
course_title         1
credits              1
level                1
delivery             1
_merge               0
dtype: int64
Number of Duplicates: 0

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,...,gpa,credits_completed,advisor,department,course_number,course_title,credits,level,delivery,_merge
0,E5001,S1001,C102,Spring 2026,Completed,96,65.0,65.0,94.7,Avery,...,3.51,72.0,Dr. Moreno,STA,270.0,Applied Statistics,3.0,Undergraduate,Hybrid,both
1,E5002,S1001,C106,Spring 2026,Completed,81,80.0,63.0,96.6,Avery,...,3.51,72.0,Dr. Moreno,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
2,E5003,S1001,C103,Spring 2026,Completed,77,67.0,72.0,88.6,Avery,...,3.51,72.0,Dr. Moreno,CS,126.0,Introduction to Computing,4.0,Undergraduate,In Person,both
3,E5004,S1002,C106,Fall 2025,Completed,86,NaN,85.0,77.3,Maya,...,2.71,108.0,Dr. Shah,STA,556.0,Statistics and Data Science Computing Workflows,3.0,Graduate,In Person,both
4,E5005,S1002,C101,Fall 2025,Completed,90,55.0,79.0,85.8,Maya,...,2.71,108.0,Dr. Shah,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both

In [68]:
print(f"students IDs Missing from final_df: {set(students["student_id"]) - set(final_df["student_id"])}\n")
print(f"courses IDs Missing from final_df: {set(courses["course_id"]) - set(final_df["course_id"])}\n")
print(f"enrollments IDs Missing from final_df: {set(enrollments["enrollment_id"]) - set(final_df["enrollment_id"])}\n")

students IDs Missing from final_df: {'S1030'}

courses IDs Missing from final_df: set()

enrollments IDs Missing from final_df: set()

In [69]:
final_df.loc[final_df["_merge"] != "both"]

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,...,gpa,credits_completed,advisor,department,course_number,course_title,credits,level,delivery,_merge
58,E5059,S1008,C999,Fall 2026,Enrolled,79,82.0,86.0,89.0,Lucas,...,2.89,45.0,Dr. Shah,NaN,NaN,NaN,NaN,NaN,NaN,left_only

There are duplicate students and duplicate courses because one student can be enrolled in multiple courses, and courses can have multiple students. The many - to - one relationships used here indicate the many enrollments for each student and course. 

Student S1030 is not enrolled in any courses, and is therefore not in the final dataset.

# Part 4: Missing Data and Reshaping

1. report missing counts and percentages;
2. identify rows with missing values in one important variable;
3. reshape one part of the data using either melt, pivot, or pivot_table;
4. explain why automatically replacing every missing value with zero would be inappropriate

In [70]:
pct_missing = final_df.isna().mean()*100
num_missing = final_df.isna().sum()

missingness_df = pd.DataFrame({"pct_missing" : pct_missing, "num_missing" : num_missing})
missingness_df

                   pct_missing  num_missing
enrollment_id         0.000000            0
student_id            0.000000            0
course_id             0.000000            0
term                  0.000000            0
status                0.000000            0
midterm_score         0.000000            0
final_score           8.474576            5
project_score         5.084746            3
attendance_pct        3.389831            2
first_name            1.694915            1
last_name             1.694915            1
program               1.694915            1
year                  1.694915            1
age                   8.474576            5
active                1.694915            1
entry_term            1.694915            1
gpa                   8.474576            5
credits_completed     1.694915            1
advisor               3.389831            2
department            1.694915            1
course_number         1.694915            1
course_title          1.694915            1
credits               1.694915            1
level                 1.694915            1
delivery              1.694915            1
_merge                0.000000            0

In [71]:

final_df.loc[final_df["gpa"].isna()][["student_id", "first_name", "gpa", "final_score", "program", "level"]]

   student_id first_name  gpa  final_score           program          level
9       S1005      Ethan  NaN         57.0  Computer Science  Undergraduate
10      S1005      Ethan  NaN         55.0  Computer Science  Undergraduate
43      S1022     Julian  NaN         74.0        Statistics  Undergraduate
44      S1022     Julian  NaN         61.0        Statistics  Undergraduate
57      S9999        NaN  NaN         88.0               NaN       Graduate

In [72]:
# Table of average GPA per student year per class
pd.pivot_table(
    final_df,
    index = "course_title",
    columns= "year",
    values="gpa",
    aggfunc="mean"
)

year,1st,2nd,3rd,4th
course_title,,,,
Applied Statistics,3.044000,3.095000,NaN,3.1100
Databases,3.790000,3.386667,NaN,3.9500
Exploratory Data Analysis,2.685000,3.480000,3.520,2.8900
Introduction to Computing,3.630000,3.750000,3.070,3.3000
Linear Algebra,NaN,2.815000,NaN,3.0625
Probability,NaN,2.900000,3.070,3.1550
Statistical Computing,3.790000,3.050000,3.665,3.9500
Statistics and Data Science Computing Workflows,2.903333,3.596667,NaN,3.8500

Automatically replacing every value with zero would hide reasons for value missingness. For example, based on the above pivot table, Linear Algebra and Probability are not offered to first year students. Additionally, filling zeroes for missing GPAs in the pivot table would lower the course average GPAs in a way that does not reflect the performance of students who actually finished the respective course.

In [75]:
# Save final dataset
final_df.to_csv("data/processed/final_df.csv", index=False)