## DataFrames, Indexing, Slicing & Filtering
Tools: Python, pandas, VS Code and/or Jupyter

### Learning objectives
By the end of this tutorial, you should be able to:

create and inspect pandas DataFrames;

distinguish Series from DataFrames;

select columns;

select rows using .loc and .iloc;

slice rows and columns;

create Boolean conditions;

filter with one or several conditions;

use .isin(), .isna(), and .notna();

modify selected observations with .loc;

translate statistical inclusion criteria into reproducible code;

validate a filtered dataset.

In [19]:
import pandas as pd

In [20]:
data = {
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"],
    "score": [81, 94, 88, 72, 91, 85]
}

df = pd.DataFrame(data)

In [21]:
print(f"{df=}")
print(f"{df.head()=}")
print(f"{df.shape=}")
print(f"{df.columns=}")
print(f"{df.index=}")
print(f"{df.dtypes=}")
print(f"{df.info()=}")
print(f"{df.describe()=}")

df=    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  104   19     B     72
4  105   42     A     91
5  106   35     B     85
df.head()=    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  104   19     B     72
4  105   42     A     91
df.shape=(6, 4)
df.columns=Index(['id', 'age', 'group', 'score'], dtype='str')
df.index=RangeIndex(start=0, stop=6, step=1)
df.dtypes=id       int64
age      int64
group      str
score    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6 non-null      int64
 1   age     6 non-null      int64
 2   group   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 330.0 bytes
df.info()=None
df.describe()=               id        age      score
count    6.000000   6.000000   6.000000
mean   103.500000  29.666667  85.166667
std      1.870829   8.189424   7.884584
min    101.000000  19.000000  72.000000
25%    102.250000  24.750000  82.000000
50%    103.500000  29.000000  86.500000
75%    104.750000  34.000000  90.250000
max    106.000000  42.000000  94.000000

In [22]:
age = df["age"]
type(age)

pandas.Series

In [23]:
age_df = df[["age"]]
type(age_df)

pandas.DataFrame

df["age"] selects just the column as a pd.Series, while df[["age"]] returns the vector as a dataframe datatype.

In [24]:
analysis_df = df[["id", "group", "score"]]
analysis_df

    id group  score
0  101     A     81
1  102     B     94
2  103     A     88
3  104     B     72
4  105     A     91
5  106     B     85

In [25]:
print(f"\n{df.iloc[0]=}")
print(f"\n{df.iloc[0:3]=}")
print(f"\n{df.iloc[[0, 2, 5]]=}")
print(f"\n{df.iloc[1:4, 1:3]=}")

df.iloc[0]=id       101
age       24
group      A
score     81
Name: 0, dtype: object

df.iloc[0:3]=    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88

df.iloc[[0, 2, 5]]=    id  age group  score
0  101   24     A     81
2  103   27     A     88
5  106   35     B     85

df.iloc[1:4, 1:3]=   age group
1   31     B
2   27     A
3   19     B

The first argumnet to `iloc()` controls the index of the rows selected, the second controls the columns. The stop value is not included in positonal slicing.

In [26]:
df = df.set_index("id")
print(f"{df= }")
print(f"{df.index= }")

df=      age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91
106   35     B     85
df.index= RangeIndex(start=101, stop=107, step=1, name='id')

In [34]:
print(f"{df.loc[101] = }")
# df.loc[0] is no longer available because the ID 0 does not exist. 
# They both should indicate the first line, but the ID of the first line is no longer 0

# Using iloc works with 0 becuase this is the index value, not the ID value
print(f"{df.iloc[0] = }")

df.loc[101] = age      24
group     A
score    81
Name: 101, dtype: object
df.iloc[0] = age      24
group     A
score    81
Name: 101, dtype: object

In [33]:
df.loc[[102, 104, 106], ["age", "group", "score"]]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

In [35]:
small = pd.DataFrame(
    {"value": [10, 20, 30, 40]},
    index=[101, 205, 310, 412]
)

print(f"{small.loc[205] = }")
print(f"{small.iloc[1] = }")

small.loc[205] = value    20
Name: 205, dtype: int64
small.iloc[1] = value    20
Name: 205, dtype: int64

loc uses a named index value in the df, iloc uses positional indexing.

In [36]:
df.iloc[1:4]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72

In [37]:
df.loc[102:105]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91

Positional slicing contains up to the last position (not inclusive) while label-based slicing selects all that match the given labels. It would not make sense to make label slicing not inclusive because then we would need to know the label of the first non-included value.

In [38]:
df.loc[:, ["age", "score"]]

     age  score
id
101   24     81
102   31     94
103   27     88
104   19     72
105   42     91
106   35     85

In [40]:
df.loc[
    101:104,
    ["group", "score"]
]

    group  score
id
101     A     81
102     B     94
103     A     88
104     B     72

In [41]:
condition = df["score"] > 80

In [42]:
print(f"{condition = }")
print(f"{type(condition) = }")

condition = id
101     True
102     True
103     True
104    False
105     True
106     True
Name: score, dtype: bool
type(condition) = <class 'pandas.Series'>

True represents a score value larger than 80; false represents a score value of less than or equal to 80.

In [44]:
#younger than 30;
print(f"{df.loc[df["age"] < 30] = } ")

#in group B;
print(f"{df.loc[df["group"] == "B"] = } ")

#scoring at least 85.
print(f"{df.loc[df["score"] >= 85] = } ")

df.loc[df["age"] < 30] =      age group  score
id
101   24     A     81
103   27     A     88
104   19     B     72
df.loc[df["group"] == "B"] =      age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85
df.loc[df["score"] >= 85] =      age group  score
id
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [45]:
#Find participants who are at least 30 years old and score at least 85.
df.loc[(df["age"]>=30)&(df["score"]>=85)]

     age group  score
id
102   31     B     94
105   42     A     91
106   35     B     85

### Part 13:
Prediction : show participants in group A with a score that is at least 90

In [46]:
df.loc[
    (df["group"] == "A") &
    (df["score"] >= 90)
]

     age group  score
id
105   42     A     91

In [49]:
df.loc[
    df["score"] >= 85,
    ["age", "group", "score"]
]

     age group  score
id
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [50]:
df.loc[
    df["age"] >= 30,
    ["group", "score"]
]

    group  score
id
102     B     94
105     A     91
106     B     85

# Part 15

In [51]:
df2 = pd.DataFrame(
    {
        "id": range(201, 209),
        "group": ["A", "B", "C", "A", "C", "B", "A", "C"],
        "score": [81, 94, 88, 72, 91, 85, 79, 96]
    }
).set_index("id")

In [53]:
df2.loc[
    (df2["group"].isin(["B", "C"])) & (df2["score"]>=85)
]

    group  score
id
202     B     94
203     C     88
205     C     91
206     B     85
208     C     96

In [54]:
missing_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "age": [21, 32, None, 45, 28],
        "score": [81, None, 77, 92, 88]
    }
).set_index("id")

In [56]:
print(f"\n{missing_df = } ")
print(f"\n{missing_df.isna() = } ")
print(f"\n{missing_df.isna().sum() = } ")

missing_df =      age  score
id
1   21.0   81.0
2   32.0    NaN
3    NaN   77.0
4   45.0   92.0
5   28.0   88.0

missing_df.isna() =       age  score
id
1   False  False
2   False   True
3    True  False
4   False  False
5   False  False

missing_df.isna().sum() = age      1
score    1
dtype: int64

In [57]:
missing_df.loc[
    missing_df["score"].isna()
]

     age  score
id
2   32.0    NaN

In [ ]:
missing_df.loc[
    missing_df["score"].notna()
]

     age  score
id
1   21.0   81.0
3    NaN   77.0
4   45.0   92.0
5   28.0   88.0

Score = 0 is where the value of the observation was actially 0. Score = missing is where no value was observed at all. In statistical analysis, a 0 might be real value that affects the modelling and summary of the analysis. Missing values will not pull summaries or models in any direction.

In [62]:
df["performance"] = "medium" # Sets a default

df.loc[
    df["score"] >= 90,
    "performance"
] = "high"

df.loc[
    df["score"] < 80,
    "performance"
] = "low"

In [63]:
df

     age group  score performance
id
101   24     A     81      medium
102   31     B     94        high
103   27     A     88      medium
104   19     B     72         low
105   42     A     91        high
106   35     B     85      medium

In [66]:
#young → age < 30
df.loc[df["age"] < 30,
"age_group"] = "young"
#older → age >= 30
df.loc[df["age"] >= 30,
"age_group"] = "older"

df

     age group  score performance age_group
id
101   24     A     81      medium     young
102   31     B     94        high     older
103   27     A     88      medium     young
104   19     B     72         low     young
105   42     A     91        high     older
106   35     B     85      medium     older

In [67]:
df[df["score"] > 80]["score"] = 100

/tmp/ipykernel_6173/2702008686.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[df["score"] > 80]["score"] = 100

In [69]:
df.loc[
    df["score"] > 80,
    "score"
] = 100

df

     age group  score performance age_group
id
101   24     A    100      medium     young
102   31     B    100        high     older
103   27     A    100      medium     young
104   19     B     72         low     young
105   42     A    100        high     older
106   35     B    100      medium     older

The .loc verion is clearer because it sets values at an individual location and mutates the dataframe in place rather than create a copy.

In [71]:
analysis = df.loc[
    (df["age"] >= 18) &
    (df["group"] == "A") &
    (df["score"].notna())
]
analysis

     age group  score performance age_group
id
101   24     A    100      medium     young
103   27     A    100      medium     young
105   42     A    100        high     older

Older, high-performing participants
Age criterion: >= 30
Score criterion: >=85
Missing-data criterion: not na
Variables required: scores, age, group

In [76]:
eligible = (
    (df["age"] >= 30) &
    (df["score"] >= 85) &
    (df["score"].notna())
)

analysis_df = df.loc[
    eligible,
    ["age", "group", "score"]
]

print(eligible)

id
101    False
102     True
103    False
104    False
105     True
106     True
dtype: bool

In [ ]:
analysis_df

     age group  score
id
102   31     B    100
105   42     A    100
106   35     B    100

# Mini data science challenge

In [78]:
participants = pd.DataFrame(
    {
        "id": range(1001, 1011),
        "age": [22, 34, 29, 41, 19, 37, 26, 45, 31, 28],
        "group": ["A", "B", "A", "C", "B", "A", "C", "B", "A", "C"],
        "score": [78, 91, 85, 88, 72, 95, 81, 67, 90, 84]
    }
).set_index("id")

In [96]:
# A: 30 or older
older = participants.loc[participants["age"] >= 30]
# B: Groups a or c
groups_ac = participants.loc[participants["group"].isin(["A", "C"])]
# C: scores >= 85
high_scores = participants.loc[participants["score"] >= 85]
# D: at least 30 yo and 85 score
older_high = participants.loc[(participants["age"] >= 30) & (participants["score"]>= 85)]
# E: Group and score for high scorers
high_score_summary = participants.loc[(participants["score"] >= 85), ["group", "score"]]
# F: Group A and at least score 80 
group_a_good = participants.loc[(participants["group"] == "A")&(participants["score"] >= 80)]
# G: Not group B
not_group_b = participants.loc[participants["group"] != "B"]

In [113]:
dfs = [older,
groups_ac,
high_scores,
older_high,
high_score_summary,
group_a_good,
not_group_b]

In [114]:
for df in dfs:
    print(f"\n===================================\n")
    print(f"\n{df.shape = }")
    print(f"\n{df.head() = }")
    print(f"\n{df.index = }")
    print(f"\n")

===================================


df.shape = (5, 3)

df.head() =       age group  score
id
1002   34     B     91
1004   41     C     88
1006   37     A     95
1008   45     B     67
1009   31     A     90

df.index = Index([1002, 1004, 1006, 1008, 1009], dtype='int64', name='id')



===================================


df.shape = (7, 3)

df.head() =       age group  score
id
1001   22     A     78
1003   29     A     85
1004   41     C     88
1006   37     A     95
1007   26     C     81

df.index = Index([1001, 1003, 1004, 1006, 1007, 1009, 1010], dtype='int64', name='id')



===================================


df.shape = (5, 3)

df.head() =       age group  score
id
1002   34     B     91
1003   29     A     85
1004   41     C     88
1006   37     A     95
1009   31     A     90

df.index = Index([1002, 1003, 1004, 1006, 1009], dtype='int64', name='id')



===================================


df.shape = (4, 3)

df.head() =       age group  score
id
1002   34     B     91
1004   41     C     88
1006   37     A     95
1009   31     A     90

df.index = Index([1002, 1004, 1006, 1009], dtype='int64', name='id')



===================================


df.shape = (5, 2)

df.head() =      group  score
id
1002     B     91
1003     A     85
1004     C     88
1006     A     95
1009     A     90

df.index = Index([1002, 1003, 1004, 1006, 1009], dtype='int64', name='id')



===================================


df.shape = (3, 3)

df.head() =       age group  score
id
1003   29     A     85
1006   37     A     95
1009   31     A     90

df.index = RangeIndex(start=1003, stop=1012, step=3, name='id')



===================================


df.shape = (7, 3)

df.head() =       age group  score
id
1001   22     A     78
1003   29     A     85
1004   41     C     88
1006   37     A     95
1007   26     C     81

df.index = Index([1001, 1003, 1004, 1006, 1007, 1009, 1010], dtype='int64', name='id')

In [ ]:
def select_high_scores(data: pd.DataFrame, minimum_score: float) -> pd.DataFrame:
    return data.loc[date["score"] >= minimum_score]